version: 2.1

jobs:
  deployProd:
    machine: true
    steps:
      - run: echo "deploy production build"
  deploy_backend:
    machine: true
    steps:
      - run: echo "fait des saucisses"
  integration_tests_backend:
    machine: true
    steps:
      -run: echo "tests"
  acceptances1:
    machine: true
    steps:
      - run: echo "acceptance tests 1-5"
  checkoutAndTest:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "unit tests"
  acceptances2:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances3:
    machine: true
    steps:
      - run: echo "acceptance tests 6-10"
  acceptances4:
    machine: true
    steps:
      - run: echo "allo j'aime les pogo"
  deployStaging:
    machine: true
    steps:
      - run: echo "deploy staging"
workflows:
  build:
    jobs:
      - checkoutAndTest
      - deploy_backend:
        requires:
          - checkoutAndTest
      - integration_tests_backend:
          requires:
            - deploy_backend
      - deployStaging:
          requires:
            - integration_tests_backend
      - acceptances1:
          requires:
            - deployStaging
      - acceptances2:
          requires:
            - deployStaging
      - acceptances3:
          requires:
            - deployStaging
      - acceptances4:
          requires:
            - deployStaging
      - deployProd:
          requires:
            - acceptances1
            - acceptances2
            - acceptances3
            - acceptances4